import json
import os
from datetime import datetime, timezone

import boto3

from scanners.tag_scanner import scan_security_group_tags
from scanners.security_group_scanner import scan_security_group_exposure
from scanners.cost_scanner import scan_unattached_volumes


dynamodb = boto3.resource("dynamodb")
sns = boto3.client("sns")

TABLE_NAME = os.environ["FINDINGS_TABLE_NAME"]
ALERT_TOPIC_ARN = os.environ["ALERT_TOPIC_ARN"]

table = dynamodb.Table(TABLE_NAME)


def build_finding_id(finding):
    return (
        f"{finding['control_id']}#"
        f"{finding['resource_id']}"
    )

def store_or_update_finding(finding):
    now = datetime.now(timezone.utc).isoformat()
    finding_id = build_finding_id(finding)

    response = table.get_item(
        Key={"finding_id": finding_id}
    )

    existing_item = response.get("Item")

    if existing_item:
        previous_status = existing_item.get(
            "status",
            "OPEN",
        )

        # A previously resolved issue that has returned
        # should be treated as newly actionable.
        is_new = previous_status == "RESOLVED"

        scan_count = int(
            existing_item.get("scan_count", 1)
        ) + 1

        first_detected_at = existing_item.get(
            "first_detected_at",
            now,
        )
    else:
        is_new = True
        scan_count = 1
        first_detected_at = now

    item = {
        **finding,
        "finding_id": finding_id,
        "first_detected_at": first_detected_at,
        "last_detected_at": now,
        "scan_count": scan_count,
        "status": "OPEN",
    }

    table.put_item(Item=item)

    return {
        **item,
        "is_new": is_new,
    }

def resolve_missing_findings(current_finding_ids):
    now = datetime.now(timezone.utc).isoformat()
    resolved_findings = []

    response = table.scan()

    stored_findings = response.get("Items", [])

    for item in stored_findings:
        finding_id = item["finding_id"]
        status = item.get("status", "OPEN")

        if (
            status == "OPEN"
            and finding_id not in current_finding_ids
        ):
            table.update_item(
                Key={
                    "finding_id": finding_id
                },
                UpdateExpression=(
                    "SET #status = :resolved, "
                    "resolved_at = :resolved_at"
                ),
                ExpressionAttributeNames={
                    "#status": "status"
                },
                ExpressionAttributeValues={
                    ":resolved": "RESOLVED",
                    ":resolved_at": now,
                },
            )

            resolved_findings.append(
                finding_id
            )

            print(
                f"Finding resolved: {finding_id}"
            )

    print(
        f"{len(resolved_findings)} "
        "finding(s) automatically resolved."
    )

    return resolved_findings


def send_high_severity_alert(findings):
    high_findings = [
        finding
        for finding in findings
        if (
            finding.get("severity") == "HIGH"
            and finding.get("is_new") is True
        )
    ]

    if not high_findings:
        print("No new HIGH-severity findings detected. No SNS alert sent.")
        return

    message_lines = [
        "EduCloud Guard - New HIGH Severity Security Alert",
        "",
        f"{len(high_findings)} HIGH-severity finding(s) detected.",
        "",
    ]

    for finding in high_findings:
        message_lines.extend(
            [
                f"Control: {finding['control_id']}",
                f"Resource: {finding['resource_name']}",
                f"Department: {finding['department']}",
                f"Description: {finding['description']}",
                f"Recommendation: {finding['recommendation']}",
                "",
            ]
        )

    message_lines.extend(
        [
            "Environment: NorthStar University AWS",
            "Generated by: EduCloud Guard",
        ]
    )

    sns.publish(
        TopicArn=ALERT_TOPIC_ARN,
        Subject="EduCloud Guard - New HIGH Severity Alert",
        Message="\n".join(message_lines),
    )

    print(
        f"SNS alert sent for {len(high_findings)} "
        "HIGH-severity finding(s)."
    )

def lambda_handler(event, context):
    print(
        "Starting EduCloud Guard governance scan."
    )

    findings = []

    findings.extend(
        scan_security_group_tags()
    )

    findings.extend(
        scan_security_group_exposure()
    )

    findings.extend(
    scan_unattached_volumes()
    )

    stored_findings = []

    for finding in findings:
        stored = store_or_update_finding(
            finding
        )

        stored_findings.append(
            stored
        )

        print(
            f"Finding stored or updated: "
            f"{stored['finding_id']} "
            f"scan_count={stored['scan_count']}"
        )

    current_finding_ids = {
        finding["finding_id"]
        for finding in stored_findings
    }

    resolved_findings = resolve_missing_findings(
        current_finding_ids
    )

    send_high_severity_alert(stored_findings)

    print(
        f"Scan complete. "
        f"{len(stored_findings)} findings processed."
    )

    return {
        "statusCode": 200,
        "body": json.dumps(
            {
                "findings_detected": len(
                    stored_findings
                ),
                "findings_resolved": len(resolved_findings),
                "findings": stored_findings,
            },
            default=str,
        ),
    }
